### ISSUE TITLE
Part 1

### ISSUE THREAD

**Issue by drkostas** [NLPaladins/rinehartAnalysis_questionAnswering#2]
For the first part, use the pre-trained Bert model from hugging face (Links to an external site.) and feed it with the five 300 words long sections from the book of your choice.
These sections should be selected so they are: 
- [x] introducing the protagonist(s)
- [x] the antagonist
- [x] the crime and crime scene
- [x] any significant evidence
- [x] and the resolution of the crime/a narrative that presents the case against the perpetrator.

The questions you should ask are about the identity and characteristics of the protagonist, antagonist/perpetrator, the nature and the setting of the crime or crime scene, the evidence, and the case against the perpetrator. 
Document the questions, ask the questions and document the specificity and accuracy of the results. 
Then, feed the whole novel as a context, and repeat the questions. Document the results.

**Comment by LaneMatthewJ** [comment]
[Sections Circular Staircase.md](https://github.com/NLPaladins/rinehartAnalysis_questionAnswering/files/7609680/Sections.Circular.Staircase.md)

Up for debate, but this is my attempt at consolidating the information and questions
(posted in slack on Wednesday - but wanted to have it here for posterity*)

**Comment by drkostas** [comment]
[Sections.Circular.Staircase.md](https://github.com/NLPaladins/rinehartAnalysis_questionAnswering/files/7610411/Sections.Circular.Staircase.md)

Added some extra questions
